### ISSUE TITLE
get_shared_ciphers() returns undef on OpenBSD 6.8

### ISSUE THREAD

**Issue by DabeDotCom** [radiator-software/p5-net-ssleay#232]
Something must have changed [somewhere between](https://github.com/libressl-portable/openbsd/compare/libressl-v3.1.1...libressl-v3.2.2) **LibreSSL 3.1.1** (OpenBSD 6.7) and **LibreSSL 3.2.2** (OpenBSD 6.8), because now `Net::SSLeay` is failing to `make test`

```
openbsd68% cpanm Net::SSLeay
...
# Testing Net::SSLeay 1.88
# 
# Perl information:
#   Version:         '5.030003'
#   Executable path: '/usr/bin/perl'
# 
# libssl information:
#   SSLEAY_VERSION:      'LibreSSL 3.2.2'
#   SSLEAY_CFLAGS:       'compiler: information not available'
#   SSLEAY_BUILT_ON:     'built on: date not available'
#   SSLEAY_PLATFORM:     'platform: information not available'
#   SSLEAY_DIR:          'OPENSSLDIR: "/etc/ssl"'
#   OPENSSL_ENGINES_DIR: 'ENGINESDIR: N/A'
t/local/03_use.t ....................... ok   
t/local/04_basic.t ..................... ok     
t/local/05_passwd_cb.t ................. ok     
t/local/06_tcpecho.t ................... ok   
t/local/07_sslecho.t ................... 1/102 
#   Failed test 'get_shared_ciphers'
#   at t/local/07_sslecho.t line 102.
#                   undef
#     doesn't match '(?^:(AES|RSA|SHA|CBC|DES))'
```

etc.  (There are about eight of those errors...)

I don't know whether `get_shared_ciphers` itself is the culprit, or if that's just a manifestation of something deeper, because there are a half-dozen other failures later on:

```
#   Failed test 'Verify result is X509_V_ERR_NO_EXPLICIT_POLICY'
#   at t/local/36_verify.t line 121.
#          got: '1'
#     expected: '43'


#   Failed test 'Server Finished is not empty'
#   at t/local/43_misc_functions.t line 155.

#   Failed test 'Client Finished is not empty'
#   at t/local/43_misc_functions.t line 162.

#   Failed test 'Server and Client Finished are not equal'
#   at t/local/43_misc_functions.t line 168.
Use of uninitialized value in numeric eq (==) at t/local/43_misc_functions.t line 205.
Use of uninitialized value in concatenation (.) or string at t/local/43_misc_functions.t line 205.

#   Failed test 'keyblock size 88 is the expected value '
#   at t/local/43_misc_functions.t line 205.

#   Failed test 'Net:SSLeay::version return value 772 matches get_version string'
#   at t/local/43_misc_functions.t line 219.
#          got: undef
#     expected: '772'
```

**Comment by h-vn** [comment]
> Something must have changed [somewhere between](https://github.com/libressl-portable/openbsd/compare/libressl-v3.1.1...libressl-v3.2.2) **LibreSSL 3.1.1** (OpenBSD 6.7) and **LibreSSL 3.2.2** (OpenBSD 6.8), because now `Net::SSLeay` is failing to `make test`

It's likely related to TLS 1.3 support. Do you know if TLS 1.3 compatibility is still work-in-progress, or are these changes intentional?

Here's an excerpt from LibreSSL ChangeLog file:
```
3.2.0 - Development release

        * Enable TLS 1.3 server side in addition to client by default.
          With this change TLS 1.3 is handled entirely on the new stack
          and state machine, with fallback to the legacy stack and
          state machine for older versions. Note that the OpenSSL TLS 1.3
          API is not yet visible/available.
```
Later releases have then enabled more TLS 1.3 functionality. However,  for example macro TLS1_3_VERSION is not defined even by the latest 3.3.1 release and this is a part of why tests have problems.

> ```
> #   Failed test 'get_shared_ciphers'
> #   at t/local/07_sslecho.t line 102.
> #                   undef
> #     doesn't match '(?^:(AES|RSA|SHA|CBC|DES))'
> ```

If tests are changed to allow up to TLS 1.2, these errors don't occur. The tests also succeed with OpenSSL + TLS 1.3. For some reason LibreSSL seems not to return shared ciphers with TLS 1.3.
 
>``` I don't know whether `get_shared_ciphers` itself is the culprit, or if that's just a manifestation of something deeper, because there are a half-dozen other failures later on:```

It seems it's deeper in the sense that for me it looks like not everything is implemented yet. Here's one more snippet from LibreSSL change log:

```
3.2.2 - Stable release

        * This is the first stable release with the new TLSv1.3
          implementation enabled by default for both client and server. The
          OpenSSL 1.1 TLSv1.3 API is not yet available and will be provided
          in an upcoming release.
```

Based on the above it could be the expected case that not all OpenSSL API calls work yet.

> ```
> #   Failed test 'Verify result is X509_V_ERR_NO_EXPLICIT_POLICY'
> #   at t/local/36_verify.t line 121.
> #          got: '1'
> #     expected: '43'
> ```

Policy test is again successful with 3.3.x so it seems to be fixed.

> ```
> #   Failed test 'Server Finished is not empty'
> #   at t/local/43_misc_functions.t line 155.
> 
> #   Failed test 'Client Finished is not empty'
> #   at t/local/43_misc_functions.t line 162.
> 
> #   Failed test 'Server and Client Finished are not equal'
> #   at t/local/43_misc_functions.t line 168.
> Use of uninitialized value in numeric eq (==) at t/local/43_misc_functions.t line 205.
> Use of uninitialized value in concatenation (.) or string at t/local/43_misc_functions.t line 205.
> ```

Finished being empty looks similar to shared ciphers being empty. That is, TLS 1.3 implementation does not (yet) cover everything OpenSSL's implementation does.

>```
> #   Failed test 'keyblock size 88 is the expected value '
> #   at t/local/43_misc_functions.t line 205.
> ```

Keyblock was not detected because OpenSSL API returns TLS_AES_256_GCM_SHA384 and LibreSSL names it AEAD-AES256-GCM-SHA384. Test does not (yet) know about the latter name:

```
% ~/opt/openssl-1.1.1i/bin/openssl ciphers -v -V -stdname|grep TLS_AES_256_GCM_SHA384
          0x13,0x02 - TLS_AES_256_GCM_SHA384 - TLS_AES_256_GCM_SHA384  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(256) Mac=AEAD

% ~/opt/libressl-3.3.1/bin/openssl ciphers -v -V|grep AEAD-AES256-GCM-SHA384
          0x13,0x02 - AEAD-AES256-GCM-SHA384  TLSv1.3 Kx=TLSv1.3  Au=TLSv1.3 Enc=AESGCM(256) Mac=AEAD
```

>```
> #   Failed test 'Net:SSLeay::version return value 772 matches get_version string'
> #   at t/local/43_misc_functions.t line 219.
> #          got: undef
> #     expected: '772'
> ```

Call to `Net::SSLeay::TLS1_3_VERSION();` should have succeeded. What happens is that Net::SSLeay::get_version returns 'TLV1.3' and Net::SSleay::version returns 772 (0x0304) but we don't have `Net::SSLeay::TLS1_3_VERSION();` because macro TLS1_3_VERSION  was not defined when Net::SSLeay was compiled. The macro exists in LibreSSL public headers but requires some `#define`s that are not enabled by default.

**Comment by chrisnovakovic** [comment]
I've just merged #328 into master, which brings support for the LibreSSL 3.2 series from version 3.2.4 onwards - please give it a try and let me know how you get on.

**Comment by DabeDotCom** [comment]
> I've just merged #328 into master, which brings support for the LibreSSL 3.2 series from version 3.2.4 onwards - please give it a try and let me know how you get on.

Thanks so much for looking into this!  👍 

OpenBSD 6.8 still fails [even after the latest `syspatch` has been applied — see below], but I get it — like you say, it ships with LibreSSL 3.2.**2** < 3.2.**4**:

> If we add support for LibreSSL's 3.2 series, I think it's likely that we'll have to withdraw support for LibreSSL 3.2.2 and 3.2.3 - they cause other failures in the test suite (some of which are described here, others caused by fixing those initial failures) and it doesn't seem right to patch the test suite so it passes on something that deviates too much from the libssl API - I'd rather not burden downstream modules with having to implement similar workarounds.

Is there a way to detect this and throw up a big, in-your-face, **WONTFIX** message?  e.g:

- **WARNING:** LibreSSL 3.2.2 is buggy; you're gonna need to either upgrade to >= 3.2.4, or use `--force`

At least that might save some poor soul a couple hours thinking they can fix the problem...  «shrug»

Cheers,

----
```
cpanm --local-lib /tmp/perl5 https://github.com/radiator-software/p5-net-ssleay/archive/refs/heads/master.zip
...

PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/local/*.t t/handle/local/*.t
t/handle/local/05_use.t ..................... ok
t/local/01_pod.t ............................ ok
t/local/02_pod_coverage.t ................... skipped: These tests are for only for release candidate testing. Enable with RELEASE_TESTING=1
# 
# Testing Net::SSLeay 1.91_01
# 
# Perl information:
#   Version:         '5.030003'
#   Executable path: '/usr/bin/perl'
#   SSLEAY_CFLAGS:       'compiler: information not available'
#   SSLEAY_BUILT_ON:     'built on: date not available'
#   SSLEAY_PLATFORM:     'platform: information not available'
#   SSLEAY_DIR:          'OPENSSLDIR: "/etc/ssl"'
#   OPENSSL_ENGINES_DIR: 'ENGINESDIR: N/A'
t/local/03_use.t ............................ ok
t/local/04_basic.t .......................... ok
t/local/05_passwd_cb.t ...................... ok
t/local/06_tcpecho.t ........................ ok

#   Failed test 'verify cb 1 called once'
#   at /usr/libdata/perl5/Test/Builder.pm line 152.

#   Failed test 'verify cb 1 wasn't called again'
#   at /usr/libdata/perl5/Test/Builder.pm line 152.

#   Failed test 'verify cb 2 called once'
#   at /usr/libdata/perl5/Test/Builder.pm line 152.

#   Failed test 'verify cb 3 wasn't called yet'
#   at /usr/libdata/perl5/Test/Builder.pm line 152.
# Looks like you planned 122 tests but ran 130.
# Looks like you failed 4 tests of 130 run.
t/local/07_sslecho.t ........................ 
Dubious, test returned 4 (wstat 1024, 0x400)
Failed 2/122 subtests 
        (less 1 skipped subtest: 119 okay)
t/local/08_pipe.t ........................... ok
t/local/09_ctx_new.t ........................ ok
t/local/10_rand.t ........................... ok
t/local/11_read.t ........................... ok
t/local/15_bio.t ............................ ok
t/local/20_functions.t ...................... ok
t/local/21_constants.t ...................... ok
t/local/22_provider.t ....................... skipped: no support for providers
t/local/22_provider_try_load.t .............. skipped: no support for providers
t/local/22_provider_try_load_zero_retain.t .. skipped: no support for providers
t/local/30_error.t .......................... ok
t/local/31_rsa_generate_key.t ............... ok
t/local/32_x509_get_cert_info.t ............. ok
t/local/33_x509_create_cert.t ............... ok
t/local/34_x509_crl.t ....................... ok
t/local/35_ephemeral.t ...................... skipped: LibreSSL and OpenSSL 1.1.0 removed support for ephemeral/temporary RSA private keys

#   Failed test 'Verify result is X509_V_ERR_NO_EXPLICIT_POLICY'
#   at t/local/36_verify.t line 131.
#          got: '1'
#     expected: '43'
# Looks like you failed 1 test of 105.
t/local/36_verify.t ......................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/105 subtests 
t/local/37_asn1_time.t ...................... ok
t/local/38_priv-key.t ....................... ok
t/local/39_pkcs12.t ......................... ok
t/local/40_npn_support.t .................... skipped: LibreSSL removed support for NPN
t/local/41_alpn_support.t ................... ok
t/local/42_info_callback.t .................. ok
t/local/43_misc_functions.t ................. ok
t/local/44_sess.t ........................... ok
t/local/45_exporter.t ....................... ok
t/local/46_msg_callback.t ................... ok
t/local/50_digest.t ......................... ok
t/local/61_threads-cb-crash.t ............... skipped: Threads not supported on this system
t/local/62_threads-ctx_new-deadlock.t ....... skipped: Threads not supported on this system
t/local/63_ec_key_generate_key.t ............ ok
t/local/64_ticket_sharing.t ................. ok
t/local/65_security_level.t ................. skipped: get/set_security_level not available with LibreSSL
t/local/65_ticket_sharing_2.t ............... ok
t/local/66_curves.t ......................... ok
t/local/kwalitee.t .......................... skipped: These tests are for only for release candidate testing. Enable with RELEASE_TESTING=1

Test Summary Report
-------------------
t/local/07_sslecho.t                      (Wstat: 1024 Tests: 130 Failed: 10)
  Failed tests:  111, 122-130
  Non-zero exit status: 4
  Parse errors: Bad plan.  You planned 122 tests but ran 130.
t/local/36_verify.t                       (Wstat: 256 Tests: 105 Failed: 1)
  Failed test:  41
  Non-zero exit status: 1
Files=44, Tests=2405, 11 wallclock secs ( 0.31 usr  0.25 sys +  8.18 cusr  1.57 csys = 10.31 CPU)
Result: FAIL
Failed 2/44 test programs. 11/2405 subtests failed.
*** Error 255 in /home/dabe/.cpanm/work/1635886191.85760/p5-net-ssleay-master (Makefile:1122 'test_dynamic')
-> FAIL Installing https://github.com/radiator-software/p5-net-ssleay/archive/refs/heads/master.zip failed. See /home/dabe/.cpanm/work/1635886191.85760/build.log for details. Retry with --force to force install it.
```

**Comment by chrisnovakovic** [comment]
> Is there a way to detect this and throw up a big, in-your-face, **WONTFIX** message? e.g:
> 
>     * **WARNING:** LibreSSL 3.2.2 is buggy; you're gonna need to either upgrade to >= 3.2.4, or use `--force`
> 
> At least that might save some poor soul a couple hours thinking they can fix the problem... «shrug»

Absolutely - in fact I meant to do that as part of #328 but it slipped my mind, sorry! #332 will take care of that.
